apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - urls:
        - https://github.com/jenkins-x/jx.git
      changes:
        - regex:
            pattern: |
              (?m)^FROM ghcr.io/jenkins-x/jx-cli-base-image:(?P<version>.*)$
            files:
              - "Dockerfile"
